endpoint = "https://agent-runtime.generativeai.us-chicago-1.oci.oraclecloud.com"
agent_endpoint_id = "ocid1.genaiagentendpoint.oc1.us-chicago-1.amaaaaaafioir7ia4v2pkj3x465nezzix45ki5x2smw3fg7prhhl5k56wita"